# Generated by Django 3.2 on 2022-06-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
